### ISSUE TITLE
The documents for agent and library are outdated

### ISSUE THREAD

**Issue by dawit1989** [hwangsaeul/hwangsae#103]
Installing hwangsae is hard and i think that comes from documentation and  some projects is archived.

**Comment by justinjoy** [comment]
Thank you for your interest. Yes, we are rushing to write codes so the documents are outdated.

We've decided to move all of the agents to _Gaeul_ module.
A small hint to run relay is to install packages onto ubuntu 20.04.

```
$ sudo add-apt-repository ppa:hwangsaeul/nightly
$ sudo apt-get update
$ sudo apt-get install gaeul2-relay-agent
```

Unfortunately, the default configuration file is missing in the package above so you might need to create conf file manually.

In my case, I used to use `/etc/gaeul2/gaeul2.ini`
```
[org/hwangsaeul/Gaeul2/Relay]
uid="relay"
sink-port=50019
source-port=60019
external-ip=""
authentication=true
master-uri=""
master-username=""
```

Then run the agent in cli.

```
$ gaeul2-relay-agent -c /etc/gaeul2/gaeul2.ini --dbus-type=session
```

I hope we can refine the manual in a few weeks.

**Comment by dawit1989** [comment]
Thanks it is very helpful 
I have two questions
1. Any rest API that i can use to control both relay and  recorder and may be source object
2. is there any example player app that i can use to my project.
Thanks in advance

**Comment by justinjoy** [comment]
> 1. Any rest API that i can use to control both relay and  recorder and may be source object

No rest API is planned for this project, but we provide some D-Bus APIs[1].
If you need more API, please open an issue.

FYI, We are not going to maintain recorder agent actually because it's a more application-specific feature than video streaming.

> 2. is there any example player app that i can use to my project.

It depends on which stream you are using, but if it is MPEG-TS, you can simply use `gst-player-1.0 srt://.....`.

>    Thanks in advance

You're welcome.

[1] https://github.com/hwangsaeul/gaeul/blob/master/gaeul/relay/org.hwangsaeul.Gaeul2.Relay.xml

**Comment by dawit1989** [comment]
Thanks Very Helpful.

**Comment by dawit1989** [comment]
Hi
Can you provide me with some end to end example
1. Generate SRT Stream from in source agent from (video device like webcam,file,RTSP or videotestsrc) with or without authentication
2. relay example- relay SRT stream from source agent with or without authentication
3. Play SRT stream from relay agent 
Thanks In advance

**Comment by justinjoy** [comment]
I opened an issue in the right place because all of the agents moved to _Gaeul_ repository.
The documentation will be finalized in that repository.
